### ISSUE TITLE
"DXR-" examples error

### ISSUE THREAD

**Issue by SirKnightTG** [NVIDIAGameWorks/GettingStartedWithRTXRayTracing#4] opened 2018-10-25 22:00 UTC
Here's a screenshot of the error I'm seeing with the DXR- examples.
![dxr-err](https://user-images.githubusercontent.com/7001777/47532967-7c204e80-d877-11e8-9efe-8753149cd5f1.jpg)

**Comment by nbentyNV** [comment] 2018-10-25 22:03
That usually means that `CreatePipelineState()` failed and crashed the driver. Usually an issue with the shader compilation

**Comment by erich666** [comment] 2018-10-29 16:09
I would try rebooting if all else fails. I have seen things get into an odd state after running for awhile, I'm not sure what that is about, but rebooting appears to help. If you figure it out, please let us know.

**Comment by Night12138** [comment] 2018-11-02 15:46
I have the same problem, and the same problem occurs in Microsoft's DX12 DXR sample, where the error is that my device does not support DXR.
I suspect that the API call at the system level may have failed, but Microsoft withdrew the 1809 update and I need to wait for the update 1809.
My GPU is INNO 3D 2080ti GAMING OC
The GPU driver version is 416.34@2018-10-10
The Windows version is 1803 build 17134.376

**Comment by erich666** [comment] 2018-11-02 21:52
Well, 1803 is required. I just got my own RTX 2080 Ti and followed all the instructions. Everything compiled and ran fine, even Sphereflake. I consider myself lucky, given the problems you've run into, but I can't reproduce the problem here on either machine, so I'm a bit stuck.

Do make sure you've pulled in the latest code - I did make [a fix](https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing/commit/d71387feeec66458ca6aa70cf0709e744767134b) four days ago that affected images. That said, the code runs without the fix, but Sphereflake looks wrong (not enough ray depth), so I'm doubtful this will help you.

If you figure out anything else, please do let us know.

**Comment by nbentyNV** [comment] 2018-11-02 22:08
@erich666 Did you upgrade the tutorials to use RS5?

**Comment by SirKnightTG** [comment] 2018-11-03 03:41
The recent change to Sphereflake did fix it for me. It was definitely amazing to see the giant number of spheres being rendered as well as the amount of reflections all at a pretty high framerate.

The Weekend one still has the above error.

**Comment by erich666** [comment] 2018-11-03 16:32
I'm surprised, but glad it worked out - I guess not setting the maximum ray depth gave some undefined behavior, different on your machine than mine.

I've added the same fix as done for Sphereflake to the "Ray Tracing in One Weekend" demo. You can either download all the code yet again, or the short version is to [go to this file](https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing/blob/master/DXR-RayTracingInOneWeekend/Passes/RayTracingInOneWeekendDemoPass.cpp#L28) and add the line shown, but instead simply:

`mpRays->setMaxRecursionDepth(16);`

Let me know if this fixes that demo for you. And, thanks again for all your help!

**Comment by erich666** [comment] 2018-11-03 16:34
Oh, and if you want to have bragging rights, set the value on [this line](https://github.com/NVIDIAGameWorks/GettingStartedWithRTXRayTracing/blob/master/DXR-Sphereflake/Passes/SphereflakeDemoPass.h#L38) from 7 to 8. This sometimes works, and other times it causes some warning on startup.

**Comment by SirKnightTG** [comment] 2018-11-03 16:47
Weekend now works!

Changing 7 to 8 in Sphereflake causes it to take longer to load, then crashes with the error above.

**Comment by erich666** [comment] 2018-11-03 17:11
Great, thanks for the quick work. I'm closing this one - we know there's definitely a limit to how far you can crank mSizeFactor. I'm sometimes able to use the value 8 (and you definitely want to test this on Release, not Debug) and it'll work fine; I just tried it on my home machine and it was fine, though took a solid amount of time to start up, maybe 10 seconds. But I've seen the Titan V be 50/50, sometimes giving an error, sometimes not (it's working right now). I find if I reboot I can usually run the demo with a level of 8.

**Closed as completed by erich666** 2018-11-03 17:11 UTC

**Comment by bailehang** [comment] 2018-11-05 06:05
Yes, DXR-RayTracingInOneWeekend project can work on my computer(GTX2080).
